### ISSUE TITLE
BVIT

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-database#151]
BVIT seems not to be supported.

**Comment by chynamyerz** [comment]
Not needed yet. Closing this because:

BVIT data should not be stored on the data archive since they are highly specialised (not regular fits at all) and it is a visitor’s instrument... not our own.

Cc-ed Encarni if she would like to offer an opinion.

Regards
Marissa
_______________________________________________________________________________
I am not aware of any restrictions on the BVIT data - I will double-check and get back to you.
Meanwhile, given that these files are very different from everything else, it is fine to not include them in the launch of the Data Archive - we can release them at a later date. 

Cheers,

Encarni
_______________________________________________________________________________
I would like to add that BVIT has no value to anyone other than the PIs for which it was taken. It requires specialised analysis tools. So unless we want to invite unwanted questions as to how to use and interpret that data, i stand by my opinion that it should not be included in the Data Archive

Regards
Marissa
